name: docs_env_regionate
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - cartopy
  - cftime
  - earthaccess
  - ipython
  - jupyterlab
  - matplotlib
  - netcdf4
  - pandoc
  - pydap
  - pytest
  - sphinx
  - nbsphinx
  - ipykernel
  - pip
